import { createFileRoute, Link } from '@tanstack/react-router'
import { publicCurrentCoas } from '~/data/research-entities'

export const Route = createFileRoute('/coa')({ head: () => ({ meta: [{ title: 'Lab Reports — OnimaChain' }, { name: 'description', content: 'Current-lot certificates of analysis for verified OnimaChain research-product inventory.' }] }), component: LabReports })

function LabReports() {
  const reports = publicCurrentCoas()
  return <div className="pt-28 pb-24 research-world"><header className="wrap research-hero"><p className="label label-cyan">Lab Reports / Certificates of Analysis</p><h1 className="display research-heading">Know the <span>Lot.</span></h1><p className="lede max-w-3xl mt-6">When a current OnimaChain research product has a lab report on file, you can see the report tied to that exact lot here.</p></header><section className="wrap mt-14"><div className="panel p-8 md:p-12"><p className="label label-cyan">Current public reports · {reports.length}</p>{reports.length === 0 ? <><h2 className="display-md text-3xl mt-4">No current-lot reports posted.</h2><p className="muted max-w-2xl mt-4">We do not show old or unrelated certificates as though they describe current inventory. Reports will appear only after a specific available product, inventory lot, and matching original laboratory PDF are verified.</p><Link to="/explore" className="btn mt-7">Explore the research library</Link></> : <div className="grid md:grid-cols-2 gap-5 mt-7">{reports.map((r) => <article key={r.id} className="panel-flat p-6"><h2 className="display-md text-xl">{r.compoundId}</h2><dl className="text-sm mt-4 grid gap-2"><div>Lot: {r.lotNumber}</div><div>Laboratory: {r.labName}</div><div>Test date: {r.testDate}</div><div>Methods: {r.methods.join(', ')}</div>{r.purityResult && <div>Reported purity: {r.purityResult}</div>}</dl><a href={r.originalPdf} target="_blank" rel="noreferrer noopener" className="btn btn-sm mt-5">View Original COA ↗</a></article>)}</div>}</div></section></div>
}
