import { createFileRoute } from '@tanstack/react-router'
import { useMemo, useState } from 'react'
import { calculateMouseStudy, type StudyInputs } from '~/data/preclinical-calculator'

export const Route = createFileRoute('/research-tools/preclinical-calculator')({ head: () => ({ meta: [{ title: 'Mouse Study Calculator — OnimaChain' }] }), component: MouseStudyCalculator })

const INITIAL: StudyInputs = { stockMassMg: 0, diluentMl: 0, mouseMassG: 0, targetDose: 0, doseUnit: 'mg/kg', animals: 0, administrations: 0, handlingLossPercent: 0 }
const fmt = (n: number, digits = 3) => Number(n.toFixed(digits)).toLocaleString()

function MouseStudyCalculator() {
  const [input, setInput] = useState<StudyInputs>(INITIAL)
  const output = useMemo(() => calculateMouseStudy(input), [input])
  const set = (field: keyof StudyInputs, value: number) => setInput((state) => ({ ...state, [field]: value }))
  const fill = output ? Math.min(100, output.volumePerAnimalUl / 100 * 100) : 0
  return <div className="pt-28 pb-24 research-world"><header className="wrap research-hero"><p className="label label-cyan">Preclinical research planning</p><h1 className="display research-heading">Mouse Study <span>Calculator.</span></h1><p className="lede max-w-3xl mt-6">Enter values from your own approved experimental protocol. This tool performs volume arithmetic; it does not recommend a compound, dose, route, or regimen.</p></header>
    <section className="wrap mt-12 grid lg:grid-cols-[1fr_1fr] gap-6"><div className="panel p-6 md:p-9"><h2 className="display-md text-2xl">Study inputs</h2><div className="calculator-fields mt-7"><NumberField label="Compound stock mass" unit="mg" value={input.stockMassMg} onChange={(n) => set('stockMassMg', n)} /><NumberField label="Research diluent volume" unit="mL" value={input.diluentMl} onChange={(n) => set('diluentMl', n)} /><NumberField label="Mouse body mass" unit="g" value={input.mouseMassG} onChange={(n) => set('mouseMassG', n)} /><div className="calculator-field"><label htmlFor="target-dose">Target experimental dose</label><div className="flex gap-2"><input id="target-dose" type="number" min="0" step="any" value={input.targetDose || ''} onChange={(e) => set('targetDose', Number(e.target.value))} /><select aria-label="Dose unit" value={input.doseUnit} onChange={(e) => setInput((state) => ({ ...state, doseUnit: e.target.value as StudyInputs['doseUnit'] }))}><option>mg/kg</option><option>µg/kg</option></select></div></div><NumberField label="Number of animals" unit="animals" value={input.animals} onChange={(n) => set('animals', n)} integer /><NumberField label="Number of administrations" unit="times" value={input.administrations} onChange={(n) => set('administrations', n)} integer /><NumberField label="Expected handling loss" unit="% optional" value={input.handlingLossPercent} onChange={(n) => set('handlingLossPercent', n)} allowZero /></div></div>
    <div className="panel p-6 md:p-9"><p className="label label-cyan">Calculated from your inputs</p><h2 className="display-md text-2xl mt-2">Bench worksheet</h2>{output ? <><div className="calculator-results mt-7"><Result label="Stock concentration" value={`${fmt(output.concentrationMgMl)} mg/mL`} /><Result label="Experimental dose per animal" value={`${fmt(output.dosePerAnimalMg, 5)} mg`} /><Result label="Volume per animal" value={`${fmt(output.volumePerAnimalUl, 2)} µL`} /><Result label="Total solution required" value={`${fmt(output.totalSolutionMl, 3)} mL`} /><Result label="Total compound required" value={`${fmt(output.totalCompoundMg, 4)} mg`} /><Result label="Volume with handling allowance" value={`${fmt(output.volumeWithAllowanceMl, 3)} mL`} /></div>{!output.stockSufficient && <p role="alert" className="text-amber-200 text-sm mt-5">The prepared stock is insufficient for this study plus the entered handling allowance.</p>}<div className="pipette-scene mt-8" role="img" aria-label={`Conceptual graduated laboratory vessel showing ${fmt(output.volumePerAnimalUl, 2)} microliters; visual scale capped at 100 microliters`}><div className="pipette-tube"><div className="pipette-fill" style={{ height: `${fill}%` }} /><div className="pipette-marks" /></div><p><strong>{fmt(output.volumePerAnimalUl, 2)} µL</strong><span>per animal · vessel illustration scaled to 100 µL; values above 100 µL fill the display but retain their numeric result</span></p></div></> : <p className="muted mt-8">Enter positive protocol values to calculate. Handling loss may be zero.</p>}</div></section><div className="wrap mt-10 text-sm muted max-w-4xl">Laboratory planning only. No human-equivalent dose, injection instructions, syringe units, compound-specific presets, or medical advice. Confirm calculations and protocol suitability independently before any experiment.</div></div>
}

function NumberField({ label, unit, value, onChange, integer = false, allowZero = false }: { label: string; unit: string; value: number; onChange: (value: number) => void; integer?: boolean; allowZero?: boolean }) { const id = label.toLowerCase().replaceAll(' ', '-'); return <div className="calculator-field"><label htmlFor={id}>{label}</label><div className="flex gap-2"><input id={id} type="number" min={allowZero ? '0' : integer ? '1' : '0'} step={integer ? '1' : 'any'} value={value || (allowZero ? 0 : '')} onChange={(e) => onChange(Number(e.target.value))} /><span>{unit}</span></div></div> }
function Result({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div> }
