import { createFileRoute, Link } from '@tanstack/react-router'
import { useMemo, useState } from 'react'
import { RESEARCH_COMPOUNDS, TARGETS, type TargetId } from '~/data/research-entities'

export const Route = createFileRoute('/targets')({ head: () => ({ meta: [{ title: 'Follow the Signal — OnimaChain' }] }), component: TargetsPage })

function TargetsPage() {
  const [selected, setSelected] = useState<TargetId[]>([])
  const rows = useMemo(() => RESEARCH_COMPOUNDS.filter((c) => selected.length > 0 && selected.every((id) => c.targets.includes(id))), [selected])
  const toggle = (id: TargetId) => setSelected((ids) => ids.includes(id) ? ids.filter((x) => x !== id) : [...ids, id])
  return <div className="pt-28 pb-24 research-world targets-world"><header className="wrap research-hero"><p className="label label-cyan">Target atlas / pathways, not products</p><h1 className="display research-heading">Follow the <span>Signal.</span></h1><p className="lede max-w-3xl mt-6">See which receptors each molecule is designed to interact with—and where different compounds overlap. Select more than one target to find their intersection.</p></header>
    <section className="wrap mt-14 grid lg:grid-cols-[1fr_1.1fr] gap-8"><div className="research-target-field" aria-label="Receptor targets">{TARGETS.map((t, i) => <button key={t.id} className="research-target-node" style={{ '--node-index': i } as React.CSSProperties} aria-pressed={selected.includes(t.id)} onClick={() => toggle(t.id)}><span className="research-node-light" /><strong>{t.label}</strong><small>{t.explanation}</small></button>)}</div><div className="panel p-6 md:p-9 self-start"><div className="flex items-start justify-between gap-4"><div><p className="label label-cyan">Selected signal</p><h2 className="display-md text-2xl mt-2">{selected.length ? selected.map((id) => TARGETS.find((t) => t.id === id)?.label).join(' + ') : 'Choose a receptor'}</h2></div>{selected.length > 0 && <button className="btn btn-sm" onClick={() => setSelected([])}>Clear</button>}</div><p className="text-sm muted mt-4">{selected.length ? `${rows.length} mapped compound${rows.length === 1 ? '' : 's'} match every selected target.` : 'Targets are mapped only where the identity is supported; an unlisted target is not a claim of no activity.'}</p><div className="grid gap-2 mt-7">{rows.map((c) => <Link key={c.id} to={c.researchStatus === 'WATCHLIST' ? '/watchlist/$slug' : '/compound/$slug'} params={{ slug: c.id }} className="research-target-result"><span><strong>{c.name}</strong><small>{c.researchStatus === 'WATCHLIST' ? 'Watchlist' : 'Core library'} · Informational profile</small></span><span aria-hidden>↗</span></Link>)}</div>{selected.length > 0 && rows.length === 0 && <p className="text-sm muted mt-6">No compound in the mapped set matches this combination. This map is not exhaustive.</p>}</div></section>
    <div className="wrap mt-16 border-t hairline pt-6 text-sm muted max-w-4xl">This is a curated target index, not a measured binding-affinity comparison. A receptor relationship is not proof of a clinical outcome.</div></div>
}
