// Plain-language copy pass. Exact string replacements; the run fails if any "from" is missing so nothing drifts silently.
// Scientific names, numbers, PMIDs, sequences and molecular weights are left alone on purpose.
import { readFileSync, writeFileSync } from 'node:fs'

const R = []
const rep = (file, from, to, all = false) => R.push({ file, from, to, all })

// ---------- data/signal.ts ----------
rep('src/data/signal.ts', "header: 'Corpus: 0 sources · Collection window: none · Platforms: none enabled',", "header: 'Real-world reports checked: 0 · Time window: none · Platforms connected: none',")
rep('src/data/signal.ts', "export const EMPTY_PLATFORM = 'No source access for this platform'", "export const EMPTY_PLATFORM = 'Not connected yet, so nothing is counted from here'")
rep('src/data/signal.ts', "'Public reports describe experiences; they do not establish that the compound caused those outcomes.'", "'People online describe what they felt. That is worth reading, but it does not prove the product caused it.'")
rep('src/data/signal.ts', "'Community reports are a distinct evidence class that can reveal recurring experiences but cannot independently establish causation.'", "'Stories from real people can show patterns. On their own they cannot prove cause and effect.'")
rep('src/data/signal.ts', "label: 'Source diversity', def: 'How many distinct sources (accounts, channels, publications) contribute mentions.'", "label: 'How many different voices', def: 'How many separate accounts, channels or publications the posts come from.'")
rep('src/data/signal.ts', "label: 'Independent-origin diversity', def: 'How many estimated independent origin clusters exist behind the mentions.'", "label: 'How many original stories', def: 'How many posts started on their own instead of copying someone else.'")
rep('src/data/signal.ts', "label: 'First-person proportion', def: 'Share of mentions that are first-person accounts rather than commentary.'", "label: 'First-hand vs. hearsay', def: 'How many posts are people describing their own experience rather than repeating others.'")
rep('src/data/signal.ts', "label: 'Documentation present', def: 'Share of reports with any supporting documentation (images, records, logs).'", "label: 'Comes with proof', def: 'How many reports include photos, records or logs.'")
rep('src/data/signal.ts', "label: 'Co-intervention prevalence', def: 'Share of reports that mention concurrent interventions.'", "label: 'Other things going on', def: 'How many reports mention other products or changes at the same time.'")
rep('src/data/signal.ts', "label: 'Source concentration', def: 'How much of the signal comes from a few sources.'", "label: 'A few loud voices?', def: 'How much of the chatter comes from just a handful of accounts.'")
rep('src/data/signal.ts', "label: 'Duplication / echo level', def: 'Share of mentions classified as reposts, quotations or near-duplicates.'", "label: 'Copies and reposts', def: 'How many posts are reposts, quotes or near copies.'")
rep('src/data/signal.ts', "label: 'Time dispersion', def: 'How mentions distribute over the collection window.'", "label: 'Spread over time', def: 'Whether posts came in one burst or over a long stretch.'")
rep('src/data/signal.ts', "label: 'Platform diversity', def: 'How many enabled platforms contribute mentions.'", "label: 'How many platforms', def: 'How many different sites the posts come from.'")
rep('src/data/signal.ts', "label: 'Promotional / affiliate contamination', def: 'Share of mentions with affiliate or promotional indicators.'", "label: 'Selling something?', def: 'How many posts look like ads or carry affiliate links.'")
rep('src/data/signal.ts', "label: 'Identifiable outcome description', def: 'Share of reports that name a specific observed outcome.'", "label: 'Says what happened', def: 'How many reports name a specific result instead of a vague feeling.'")
rep('src/data/signal.ts', "label: 'Follow-up availability', def: 'Share of reports with a later follow-up from the same account.'", "label: 'Came back to update', def: 'How many people posted a follow-up later.'")
rep('src/data/signal.ts', "export const NOT_ASSESSED = 'Not assessed — no corpus'", "export const NOT_ASSESSED = 'Not measured yet — no reports collected'")
rep('src/data/signal.ts', "state: 'No source access enabled' }", "state: 'Not connected' }", true)
rep('src/data/signal.ts', "state: 'Indexed — PMIDs verified via NCBI eutils at build time', enabled: true", "state: 'Connected — every PubMed ID is checked before the site is built', enabled: true")
rep('src/data/signal.ts', "state: 'Not enabled', enabled: false", "state: 'Not connected', enabled: false", true)
rep('src/data/signal.ts', "state: 'Identifiers listed; structures not fetched', enabled: false", "state: 'IDs listed; 3D files not downloaded', enabled: false")
rep('src/data/signal.ts', "{ id: 'theme', label: 'Outcome theme' }", "{ id: 'theme', label: 'What people hoped for' }")
rep('src/data/signal.ts', "{ id: 'origin', label: 'Origin', options: ['Independent origin', 'Echo', 'Unknown'] }", "{ id: 'origin', label: 'Original or copy', options: ['Original story', 'Copy or repost', 'Unknown'] }")
rep('src/data/signal.ts', "{ id: 'documentation', label: 'Documentation present' }", "{ id: 'documentation', label: 'Comes with proof' }")
rep('src/data/signal.ts', "{ id: 'combination', label: 'Single compound / combination' }", "{ id: 'combination', label: 'One product or a mix' }")
rep('src/data/signal.ts', "label: 'Independent-origin candidate', shape: 'filled point'", "label: 'Likely an original story', shape: 'filled point'")
rep('src/data/signal.ts', "label: 'Derivative discussion', shape: 'hollow point'", "label: 'Repeating someone else', shape: 'hollow point'")
rep('src/data/signal.ts', "label: 'Documented report', shape: 'ringed point'", "label: 'Report with proof attached', shape: 'ringed point'")
rep('src/data/signal.ts', "label: 'Unclear provenance', shape: 'faint point'", "label: 'Can’t tell where it came from', shape: 'faint point'")

// ---------- data/claims.ts ----------
rep('src/data/claims.ts', "{ id: 'cell', label: 'Cell' }", "{ id: 'cell', label: 'Cells in a dish' }")
rep('src/data/claims.ts', "{ id: 'larger-animal', label: 'Larger animal' }", "{ id: 'larger-animal', label: 'Bigger animal' }")
rep('src/data/claims.ts', "{ id: 'human', label: 'Human' }", "{ id: 'human', label: 'People' }")
rep('src/data/claims.ts', "{ id: 'controlled-human', label: 'Controlled human' }", "{ id: 'controlled-human', label: 'Proper human trial' }")
rep('src/data/claims.ts', "{ id: 'approved-use', label: 'Approved use' }", "{ id: 'approved-use', label: 'Approved by regulators' }")
rep('src/data/claims.ts', "'Source finding'", "'What the study said'", true)
rep('src/data/claims.ts', "'Secondary summary'", "'The summary'", true)
rep('src/data/claims.ts', "'Social interpretation'", "'The social post'", true)
rep('src/data/claims.ts', "'Viral version'", "'The viral version'", true)
rep('src/data/claims.ts', "export const ILLUSTRATIVE_BADGE = 'Illustrative wording — not an indexed source'", "export const ILLUSTRATIVE_BADGE = 'Example wording — not from a real source'")
rep('src/data/claims.ts', "'The earliest attributable support currently indexed is an ex vivo / in vitro study of tendon fibroblasts derived from rat Achilles tendon. It measured outgrowth, survival under oxidative stress and migration — not repair of an injured tendon in a living animal.'", "'The earliest study we have checked used tendon cells taken from rat Achilles tendon and grown in a dish. It measured how the cells grew, survived stress and moved. It did not test repair of an injured tendon in a living animal.'")
rep('src/data/claims.ts', "'One indexed rat study reports histopathological scores for BPC-157 that were numerically lower than control without reaching statistical significance for total scores. That is a partial relationship, not a contradiction.'", "'One rat study we checked found tissue scores for BPC-157 that were a little lower than the control group, but not by enough to count as a real difference. That partly backs the claim. It does not disprove it.'")
rep('src/data/claims.ts', "'Three indexed reviews discuss the theme but do not themselves test the claim.'", "'Three review papers talk about this topic but did not run their own test of the claim.'")
rep('src/data/claims.ts', "`No controlled human study of this outcome is indexed in ${BRAND}’s corpus. Absence from the corpus is not evidence of absence.`", "'We have not found a proper human trial of this result. That means we have not found one, not that one does not exist.'")
rep('src/data/claims.ts', "'No community signal is available: no platform source access is enabled.'", "'We are not collecting real-world reports yet, so there is nothing from people online to show here.'", true)
rep('src/data/claims.ts', "'The earliest attributable support currently indexed measured migration and invasion of a human ovarian cancer cell line treated with thymosin β4 and fragment peptides. It is an in vitro cell-line result.'", "'The earliest study we have checked measured how human ovarian cancer cells moved in a dish after being treated with thymosin β4 and pieces of it. It is a lab-dish result, not a result in a person.'")
rep('src/data/claims.ts', "'The cell line context is removed at the first mutation step; every later wording adds outcomes the origin record did not measure.'", "'The first retelling drops the fact that this was cells in a dish. Every version after that adds results the original study never measured.'")
rep('src/data/claims.ts', "'No indexed record tests this claim in an animal wound or in humans. Absence from the corpus is not evidence of absence.'", "'None of the studies we have checked test this on a real wound in an animal or in people. That means we have not found one, not that one does not exist.'")
rep('src/data/claims.ts', "  supports: 'SUPPORTS',\n  partially_supports: 'PARTIALLY_SUPPORTS',\n  contradicts: 'CONTRADICTS',\n  does_not_test: 'DOES_NOT_TEST',", "  supports: 'Backs it up',\n  partially_supports: 'Partly backs it up',\n  contradicts: 'Pushes back',\n  does_not_test: 'Talks about it, didn’t test it',")

// ---------- data/evidence.ts ----------
rep('src/data/evidence.ts', "label: 'In vitro', how: 'Verified records whose study type is in-vitro.'", "label: 'Cells in a dish (in vitro)', how: 'Checked studies done on cells in a lab dish.'")
rep('src/data/evidence.ts', "label: 'Mouse', how: 'Verified records whose title states a mouse model.'", "label: 'Mice', how: 'Checked studies whose title says it was done in mice.'")
rep('src/data/evidence.ts', "label: 'Rat', how: 'Verified records whose title states a rat model.'", "label: 'Rats', how: 'Checked studies whose title says it was done in rats.'")
rep('src/data/evidence.ts', "label: 'Other animal', how: 'Verified records whose title states another animal model.'", "label: 'Other animals', how: 'Checked studies whose title names another animal.'")
rep('src/data/evidence.ts', "label: 'Observational human', how: 'Verified records typed observational-human.'", "label: 'People, observed', how: 'Checked studies that watched people without a controlled trial.'")
rep('src/data/evidence.ts', "label: 'Case report', how: 'Verified records whose publication type is Case Reports.'", "label: 'Single-person reports', how: 'Checked reports about one patient (case reports).'")
rep('src/data/evidence.ts', "label: 'Phase I', how: 'Verified records whose publication type is Clinical Trial, Phase I.'", "label: 'Phase I trial', how: 'Checked early safety trials in a small group of people.'")
rep('src/data/evidence.ts', "label: 'Phase II', how: 'Verified records whose publication type is Clinical Trial, Phase II.'", "label: 'Phase II trial', how: 'Checked mid-size trials testing whether it works.'")
rep('src/data/evidence.ts', "label: 'Phase III', how: 'Verified records whose publication type is Clinical Trial, Phase III.'", "label: 'Phase III trial', how: 'Checked large trials, the kind regulators look at.'")
rep('src/data/evidence.ts', "label: 'Approved indication', how: 'Not assessed — no regulatory record indexed.'", "label: 'Approved use', how: 'Not checked yet — we have not connected regulator records.'")
rep('src/data/evidence.ts', "label: 'Replication', how: 'Not assessed — replication relationships are not yet indexed.'", "label: 'Repeated by others', how: 'Not checked yet — we do not track repeat studies yet.'")
rep('src/data/evidence.ts', "label: 'Independent groups', how: 'Distinct last-author surnames among verified records (proxy).'", "label: 'Separate research teams', how: 'How many different senior authors the checked studies have. A rough stand-in for separate teams.'")
rep('src/data/evidence.ts', "label: 'Mechanistic', how: 'Verified records tagged mechanistic from their abstract.'", "label: 'How it works', how: 'Checked studies that looked at the mechanism, based on their summary.'")
rep('src/data/evidence.ts', "label: 'Safety characterization', how: 'Not assessed — no safety-typed record indexed.'", "label: 'Safety', how: 'Not checked yet — no safety study has been added.'")
rep('src/data/evidence.ts', "label: 'Research age', how: 'Earliest to latest publication year among verified records.'", "label: 'Years of research', how: 'From the oldest to the newest checked study.'")
rep('src/data/evidence.ts', "label: 'Vascular signaling'", "label: 'Blood-vessel signaling'")
rep('src/data/evidence.ts', "label: 'Actin-related mechanisms'", "label: 'How cells move (actin)'")
rep('src/data/evidence.ts', "label: 'Public recovery discussion'", "label: 'Recovery talk online'")
rep('src/data/evidence.ts', "label: 'Tissue-repair discussion'", "label: 'Tissue-repair talk online'")
rep('src/data/evidence.ts', "label: 'Studies indexed & verified', value: v.length, of: STUDIES.length, at: verifiedAt, note: 'PMIDs resolved against NCBI eutils at build time'", "label: 'Studies checked', value: v.length, of: STUDIES.length, at: verifiedAt, note: 'Every PubMed ID confirmed against PubMed before the site was built'")
rep('src/data/evidence.ts', "note: 'ClinicalTrials.gov connector not enabled'", "note: 'ClinicalTrials.gov not connected yet'")
rep('src/data/evidence.ts', "note: 'No regulatory connector enabled'", "note: 'Regulator records not connected yet'")
rep('src/data/evidence.ts', "label: 'Claims materially changed'", "label: 'Claims we updated'")
rep('src/data/evidence.ts', "note: 'From claims.ts change history'", "note: 'From our change log'")
rep('src/data/evidence.ts', "label: 'New source clusters', value: 0, of: null, at: null, note: 'No platform source access enabled'", "label: 'New real-world report groups', value: 0, of: null, at: null, note: 'Social platforms not connected yet'")
rep('src/data/evidence.ts', "label: 'Compounds in atlas'", "label: 'Peptides in the collection'")

// ---------- data/lessons.ts ----------
rep('src/data/lessons.ts', "title: 'How internet claims mutate', summary: 'Scrub a finding from its abstract to its viral version and watch what each step drops.'", "title: 'How a study turns into a viral post', summary: 'Drag the slider from the real study to the viral version and watch what gets dropped along the way.'")
rep('src/data/lessons.ts', "title: 'How animal research works', summary: 'Models, endpoints and why a rat result is a rat result.'", "title: 'Why a rat result is a rat result', summary: 'What animal studies can tell you, and where they stop.'")
rep('src/data/lessons.ts', "title: 'What \"in vitro\" means', summary: 'Cells in a dish are a system, not a body.'", "title: 'Cells in a dish are not a body', summary: 'What “in vitro” means and why it matters.'")
rep('src/data/lessons.ts', "title: 'Why replication matters', summary: 'One lab, ten papers, one finding.'", "title: 'One lab, ten papers, one finding', summary: 'Why a result needs to be repeated by someone else before it counts.'")
rep('src/data/lessons.ts', "title: 'Correlation vs causation', summary: 'Why reports that co-occur are not reports that cause.'", "title: 'Happened after is not caused by', summary: 'Why two things showing up together does not mean one caused the other.'")
rep('src/data/lessons.ts', "title: 'How peptides interact with receptors', summary: 'Docking, binding and what a mechanism does and does not tell you.'", "title: 'How a peptide talks to a cell', summary: 'Receptors, binding, and what “how it works” can and can’t tell you.'")
rep('src/data/lessons.ts', "title: 'Why source independence matters', summary: 'Ten thousand posts are not ten thousand observations.'", "title: 'Ten thousand posts, one story', summary: 'Why a flood of posts can all trace back to a single source.'")
rep('src/data/lessons.ts', "title: 'Reading a research paper', summary: 'Abstract, methods, results — and the sentence people quote.'", "title: 'How to read a study in five minutes', summary: 'Summary, method, results, and the one sentence everyone quotes.'")
rep('src/data/lessons.ts', "title: 'Understanding clinical-trial phases', summary: 'Phase I to approval, and what each phase measures.'", "title: 'Phase I, II, III: what the numbers mean', summary: 'From first safety test to approval, one step at a time.'")
rep('src/data/lessons.ts', "title: 'Research vs anecdote', summary: 'Two evidence classes, kept separate on purpose.'", "title: 'A study vs. a story', summary: 'Both matter. They are not the same thing, and we never mix them.'")

// ---------- components ----------
rep('src/components/EmptyState.tsx', "export const CORPUS_ABSENCE = `No qualifying record is currently indexed in ${BRAND}’s corpus.`", "export const CORPUS_ABSENCE = `We haven’t added a checked source for this yet.`")
rep('src/components/CompoundCard.tsx', "No qualifying record is currently indexed in {BRAND}&rsquo;s corpus", "No checked source added yet")
rep('src/components/CorpusHeader.tsx', 'aria-label="Corpus definition"', 'aria-label="What these numbers are based on"')
rep('src/components/CorpusHeader.tsx', "<span>Corpus: <b", "<span>Real-world reports checked: <b")
rep('src/components/CorpusHeader.tsx', "<span>Collection window: <b", "<span>Time window: <b")
rep('src/components/CorpusHeader.tsx', "<span>Platforms: <b", "<span>Platforms connected: <b")
rep('src/components/CorpusHeader.tsx', ": 'none enabled'}", ": 'none'}")
rep('src/components/SourceCard.tsx', "<dt>Publication date</dt>", "<dt>Posted</dt>")
rep('src/components/SourceCard.tsx', "<dt>Retrieval date</dt>", "<dt>Collected</dt>")
rep('src/components/SourceCard.tsx', "<dt>First-person / commentary</dt>", "<dt>First-hand or hearsay</dt>")
rep('src/components/SourceCard.tsx', "<dt>Origin cluster</dt>", "<dt>Original or copy</dt>")
rep('src/components/StudyCard.tsx', "could not be verified at build time; it is not rendered as a citation.", "could not be confirmed on PubMed, so we do not show it as a source.")
rep('src/components/StudyCard.tsx', "relationship === 'SUPPORTS' ? 'chip-cyan' : relationship === 'CONTRADICTS' ? 'chip-amber' : ''", "relationship === 'Backs it up' ? 'chip-cyan' : relationship === 'Pushes back' ? 'chip-amber' : ''")
rep('src/components/StudyCard.tsx', "{m.authors.length} authors · last author {m.lastAuthor || 'n/a'}", "{m.authors.length} authors · senior author {m.lastAuthor || 'n/a'}")
rep('src/components/StudyCard.tsx', "— abstract, PMID {study.pmid}", "— from the study summary, PubMed ID {study.pmid}")
rep('src/components/StudyCard.tsx', "Verified {new Date(m.verifiedAt).toISOString().slice(0, 10)} via NCBI eutils esummary", "Checked against PubMed on {new Date(m.verifiedAt).toISOString().slice(0, 10)}")
rep('src/components/ClaimCard.tsx', ">Tracked research claim<", ">A claim we track<")
rep('src/components/ClaimCard.tsx', "· outcome theme: {claim.outcomeTheme}", "· about: {claim.outcomeTheme}")
rep('src/components/ClaimCard.tsx', ">Origin<", ">Started with<")
rep('src/components/ClaimCard.tsx', "{supports.length} verified record{supports.length === 1 ? '' : 's'} linked", "{supports.length} checked stud{supports.length === 1 ? 'y' : 'ies'} linked")
rep('src/components/ChangeDiff.tsx', ">altered interpretation<", ">changed our reading<")
rep('src/components/SpeciesBadge.tsx', 'title="Species not stated in the record title">Species not in title<', 'title="The study title does not say what it was tested on">Tested on: not in title<')
rep('src/components/SignalFingerprint.tsx', "title = 'Signal integrity'", "title = 'How trustworthy is the chatter?'")
rep('src/components/SignalFingerprint.tsx', ">No single score<", ">Never boiled down to one score<")
rep('src/components/SignalFingerprint.tsx', "aria-label={`Signal integrity radial: ${n} dimensions, all ${NOT_ASSESSED}`}", "aria-label={`Chatter check: ${n} questions, all ${NOT_ASSESSED}`}")
rep('src/components/SignalFingerprint.tsx', ">no corpus<", ">no reports yet<")
rep('src/components/SignalFingerprint.tsx', ">0 sources<", ">0 checked<")
rep('src/components/SignalFingerprint.tsx', 'aria-label="Signal integrity matrix"', 'aria-label="Chatter check, as a table"')
rep('src/components/SignalFingerprint.tsx', "<th>Dimension</th><th>Assessment</th>", "<th>Question</th><th>Answer</th>")
rep('src/components/EvidenceGenome.tsx', "Filled = verified records in that class · hollow = zero indexed · dashed = not assessed. Descriptive only; not a score.", "Filled = we have checked studies of that kind · hollow = none yet · dashed = not checked yet. This is a picture of what exists, not a score.")
rep('src/components/EvidenceGenome.tsx', ">Not assessed<", ">Not checked yet<")
rep('src/components/EvidenceGenome.tsx', ">0 · hollow<", ">0 · none yet<")
rep('src/components/TimelineLane.tsx', "research: 'No research event indexed beyond claim creation.'", "research: 'Nothing new since we first added this claim.'")
rep('src/components/TimelineLane.tsx', "trials: 'No trial record indexed — ClinicalTrials.gov connector not enabled.'", "trials: 'No trials listed yet — we have not connected ClinicalTrials.gov.'")
rep('src/components/TimelineLane.tsx', "regulatory: 'No regulatory record indexed.'", "regulatory: 'No regulator decisions listed yet.'")
rep('src/components/TimelineLane.tsx', "signal: 'No public-signal event indexed — no platform source access enabled.'", "signal: 'No real-world reports yet — social platforms are not connected.'")
rep('src/components/TimelineLane.tsx', "signal: 'Public signal' }", "signal: 'Real-world reports' }")
rep('src/components/nodes.tsx', "label: 'Research', shape: 'circle'", "label: 'Study', shape: 'circle'")
rep('src/components/nodes.tsx', "label: 'Community', shape: 'hexagon'", "label: 'People online', shape: 'hexagon'")
rep('src/components/nodes.tsx', "label: 'Regulatory', shape: 'square'", "label: 'Regulators', shape: 'square'")
rep('src/components/nodes.tsx', "label: 'Contradiction', shape: 'triangle'", "label: 'Pushback', shape: 'triangle'")
rep('src/components/LineageGraph.tsx', "detail: 'Canonical claim. Status: tracked research claim. Not labelled true or false.'", "detail: 'The claim itself. We track it; we do not stamp it true or false.'")
rep('src/components/LineageGraph.tsx', "'Unverified record'", "'Could not confirm this study'")
rep('src/components/LineageGraph.tsx', "' — the record discusses the theme but does not test the claim.'", "' — this paper talks about the topic but did not test the claim.'")
rep('src/components/LineageGraph.tsx', ": 'Source relationship unresolved.' })", ": 'We could not confirm how this study connects.' })")
rep('src/components/LineageGraph.tsx', "rel: ok ? RELATIONSHIP_LABEL[s.relationship] : 'UNRESOLVED'", "rel: ok ? RELATIONSHIP_LABEL[s.relationship] : 'Not confirmed'")
rep('src/components/LineageGraph.tsx', "sub: 'No source access for this platform', hollow: true, detail: `Adapter: ${p.adapter}. ${p.state}. No mention is counted.`", "sub: 'Not connected yet', hollow: true, detail: `Not connected yet, so nothing from ${p.name} is counted. (How it would connect: ${p.adapter}.)`")
rep('src/components/LineageGraph.tsx', "rel: 'NO ACCESS', unresolved: true", "rel: 'Not connected', unresolved: true")
rep('src/components/LineageGraph.tsx', "sub: 'contradicts', hollow: false", "sub: 'pushes back', hollow: false")
rep('src/components/LineageGraph.tsx', "rel: 'CONTRADICTS', unresolved: false", "rel: 'Pushes back', unresolved: false")
rep('src/components/LineageGraph.tsx', "aria-label={`Claim lineage graph with ${data.nodes.length} nodes; see node cards for a text equivalent`}", "aria-label={`Map of how this claim spread, ${data.nodes.length} points; the cards below say the same thing in text`}")
rep('src/components/LineageGraph.tsx', ">Laying out lineage…<", ">Drawing the map…<")
rep('src/components/LineageGraph.tsx', "<span>dashed = unresolved / no access</span>", "<span>dashed = not confirmed or not connected</span>")
rep('src/components/LineageGraph.tsx', ">Replay trace<", ">Play it again<")
rep('src/components/LineageGraph.tsx', ">Select a node to inspect its provenance. Hover to isolate its relationships.<", ">Click a point to see where it came from. Hover to see what it connects to.<")
rep('src/components/LineageGraph.tsx', 'aria-label="Node inspector"', 'aria-label="Details for the selected point"')
rep('src/components/TranslationTrack.tsx', "{furthest < 0 ? 'No stage supported by an indexed record' : `Indexed support reaches: ${TRANSLATION_STAGES[furthest].label} — the signal stops there`}", "{furthest < 0 ? 'None of the studies we checked reach any stage yet' : `Tested as far as: ${TRANSLATION_STAGES[furthest].label} — and no further`}")
rep('src/components/TranslationTrack.tsx', ">No outcome has an indexed translation path.<", ">We have not mapped how far any result has been tested yet.<")
rep('src/components/TranslationTrack.tsx', "{on ? 'supported by an indexed record' : 'not supported by an indexed record'}", "{on ? 'a checked study reached this stage' : 'no checked study has reached this stage'}")
rep('src/components/TranslationTrack.tsx', ">signal stops<", ">stops here<")
rep('src/components/TranslationTrack.tsx', 'aria-label={`Translation stages for ${r.outcome}`}', 'aria-label={`How far ${r.outcome} has been tested`}')
rep('src/components/MutationLadder.tsx', 'aria-label="Mutation steps"', 'aria-label="Steps from study to viral post"')
rep('src/components/MutationLadder.tsx', 'aria-label="Scrub mutation steps"', 'aria-label="Drag between the steps"')
rep('src/components/MutationLadder.tsx', ">Uncertainty removed<", ">The “maybe” got dropped<")
rep('src/components/MutationLadder.tsx', ">Larger wording = mutation, not evidence<", ">Bigger words, same evidence<")
rep('src/components/MutationLadder.tsx', "struck = dropped from the previous wording · {amplified ? 'amber' : 'violet'} = added{speciesGone ? ' · falling tags = species/context detached' : ''}{uncertaintyGone ? ' · fading words = hedges removed' : ''}. Classification links to the previous step's text above.", "crossed out = dropped from the last version · {amplified ? 'amber' : 'violet'} = added{speciesGone ? ' · falling words = the test setup got left out' : ''}{uncertaintyGone ? ' · fading words = the careful wording got removed' : ''}. Each tag compares this step to the one before it.")
rep('src/components/ProvenanceDrawer.tsx', ">Provenance · underneath the interpretation<", ">Behind the scenes · where this comes from<")
rep('src/components/ProvenanceDrawer.tsx', ">Interpretation on top · evidence underneath. Nothing here is generated from outside the indexed records.<", ">What you see on the page comes only from the sources listed here. Nothing is made up to fill space.<")
rep('src/components/StructureViewer.tsx', ">Structure provenance · underneath the render<", ">Where this 3D shape comes from<")
rep('src/components/StructureViewer.tsx', "Backbone Cα positions are generated from the residue list with alpha-helix parameters (rise 1.5 Å, 100°/residue, radius 2.3 Å); proline kinks the axis 30–40°, glycine adds a seeded wobble, lactam bridges close the ring. Nothing here was measured.", "We draw the shape from the amino-acid sequence using standard helix geometry (rise 1.5 Å, 100°/residue, radius 2.3 Å). Proline bends the chain 30–40°, glycine adds a small wobble, lactam bridges close the ring. This is a drawing based on the sequence, not a measured structure.")
rep('src/components/SourceBadge.tsx', "primary: 'Conceptual visualization', secondary: pdb ?? 'Sequence pending verification'", "primary: 'Artist’s illustration', secondary: pdb ?? 'Sequence still being confirmed'")
rep('src/components/SourceBadge.tsx', "primary: 'Sequence-derived visualization (procedural, not measured)'", "primary: 'Drawn from the sequence (not a measured structure)'")
rep('src/components/Hero.tsx', "'Static render · sequence-derived, not measured'", "'Still image · drawn from the sequence, not measured'")

// ---------- routes: claim ----------
rep('src/routes/claim.$id.tsx', "const SECTIONS = ['Origin', 'Original scope', 'Claim lineage', 'Claim mutation', 'Research support', 'Research contradictions', 'Human signal', 'Echo analysis', 'Translation state', 'Current interpretation', 'Change history']", "const SECTIONS = ['Where it started', 'What was actually tested', 'How the story spread', 'How the wording changed', 'Studies that back it', 'Studies that push back', 'What people say', 'Copies vs. originals', 'How far it has been tested', 'The short version', 'What we changed']")
rep('src/routes/claim.$id.tsx', ">Tracked research claim<", ">A claim we track<")
rep('src/routes/claim.$id.tsx', ">Not labelled true or false. Status describes tracking, not verdict.<", ">We don’t stamp claims true or false. We show you where they came from and let you decide.<")
rep('src/routes/claim.$id.tsx', '<Sec i={0} title="Origin" lede="Earliest attributable support currently indexed.">', '<Sec i={0} title="Where it started" lede="The earliest study we have checked that this claim traces back to.">')
rep('src/routes/claim.$id.tsx', 'title="Source relationship unresolved" detail="The origin record could not be verified at build time and is not rendered as a citation."', 'title="We could not confirm the source" detail="The original study could not be confirmed on PubMed, so we do not show it as a source."')
rep('src/routes/claim.$id.tsx', '<Sec i={1} title="Original scope" lede="Species, model, endpoint, wording — copied, not paraphrased.">', '<Sec i={1} title="What was actually tested" lede="Who or what it was tested on, how, what was measured, and the exact words the study used.">')
rep('src/routes/claim.$id.tsx', '<dt className="label">Species</dt>', '<dt className="label">Tested on</dt>')
rep('src/routes/claim.$id.tsx', "stated in the abstract (cells derived from rat tissue); not stated in the title", "the study summary says the cells came from rat tissue; the title does not say")
rep('src/routes/claim.$id.tsx', '<dt className="label">Model</dt>', '<dt className="label">Test setup</dt>')
rep('src/routes/claim.$id.tsx', '<dt className="label">Endpoint</dt>', '<dt className="label">What was measured</dt>')
rep('src/routes/claim.$id.tsx', '<dt className="label">Wording</dt>', '<dt className="label">The study’s own words</dt>')
rep('src/routes/claim.$id.tsx', ": 'Source relationship unresolved'}</dd>", ": 'We could not confirm the source'}</dd>")
rep('src/routes/claim.$id.tsx', '<Sec i={2} title="Claim lineage" lede="Research → interpretation → community. Every edge names its relationship; dashed edges are unresolved or have no source access.">', '<Sec i={2} title="How the story spread" lede="From the study, to the retelling, to the people online. Every line says how the two ends are connected. Dashed lines are not confirmed or not connected.">')
rep('src/routes/claim.$id.tsx', '<Sec i={3} title="Claim mutation" lede="How language changes while a claim propagates. This is not automatically misinformation; each step is classified and linked to its source text.">', '<Sec i={3} title="How the wording changed" lede="Watch a careful study result turn into a bold post. That is not always lying. But each step is tagged so you can see exactly what changed.">')
rep('src/routes/claim.$id.tsx', '<Sec i={4} title="Research support" lede="Study records and their explicit relationship to this claim.">', '<Sec i={4} title="Studies that back it" lede="Each study we checked, and exactly how it relates to this claim.">')
rep('src/routes/claim.$id.tsx', "relationship=\"SUPPORTS\" basis={origin.abstractQuote ?? null}", "relationship=\"Backs it up\" basis={origin.abstractQuote ?? null}")
rep('src/routes/claim.$id.tsx', '<Sec i={5} title="Research contradictions" lede="Null and conflicting findings, methodological criticism.">', '<Sec i={5} title="Studies that push back" lede="Results that found nothing, results that disagree, and criticism of how a study was run.">')
rep('src/routes/claim.$id.tsx', 'relationship="CONTRADICTS" basis={s.basis}', 'relationship="Pushes back" basis={s.basis}')
rep('src/routes/claim.$id.tsx', 'title="No contradictory study currently indexed" detail="A partially-supporting record (numerically lower scores without statistical significance) is listed under Research support with its exact wording. Absence from the corpus is not evidence of absence."', 'title="No study we have checked pushes back on this yet" detail="One study only partly backs it (slightly better scores, but not by enough to count). It is listed above under studies that back it, in its own words. Not finding a study is not the same as proving there is none."')
rep('src/routes/claim.$id.tsx', '<Sec i={6} title="Human signal" lede={HUMAN_SIGNAL_LINE}>', '<Sec i={6} title="What people say" lede={HUMAN_SIGNAL_LINE}>')
rep('src/routes/claim.$id.tsx', '<Sec i={7} title="Echo analysis" lede="Independent origins vs derivative mentions. Ten thousand posts are not ten thousand observations.">', '<Sec i={7} title="Copies vs. originals" lede="Ten thousand posts are not ten thousand people. We count how many stories are original and how many are reposts.">')
rep('src/routes/claim.$id.tsx', "[['Raw mentions', '0'], ['Estimated independent origin clusters', '0'], ['Derivative / echo mentions', '0']]", "[['Posts found', '0'], ['Original stories', '0'], ['Copies and reposts', '0']]")
rep('src/routes/claim.$id.tsx', "{EMPTY_PLATFORM}. No relationship (independent origin / response / repost / derivative / near duplicate / unknown) has been assigned because no mention exists in the corpus.", "Social platforms are not connected yet, so there are no posts to sort into originals and copies.")
rep('src/routes/claim.$id.tsx', '<Sec i={8} title="Translation state" lede="Where the claim has actually been tested.">', '<Sec i={8} title="How far it has been tested" lede="From cells in a dish, to animals, to people. The light stops where the checked studies stop.">')
rep('src/routes/claim.$id.tsx', ">Stages: {TRANSLATION_STAGES.map((s) => s.label).join(' → ')}<", ">The full ladder: {TRANSLATION_STAGES.map((s) => s.label).join(' → ')}<")
rep('src/routes/claim.$id.tsx', '<Sec i={9} title="Current interpretation" lede="Constrained synthesis. Every sentence maps to a record above or an explicit empty state.">', '<Sec i={9} title="The short version" lede="Our plain-English reading. Every sentence comes from a study listed above, or says clearly what we do not have.">')
rep('src/routes/claim.$id.tsx', "{BRAND} structured summary — generated from the structured records on this page, not free-form. Supporting records:", "Written by {BRAND} from the studies on this page only. Those studies:")
rep('src/routes/claim.$id.tsx', '<Sec i={10} title="Change history" lede="Every material modification. Nothing is silently rewritten.">', '<Sec i={10} title="What we changed" lede="Every real edit we have made to this claim, with before and after. Nothing gets quietly rewritten.">')
rep('src/routes/claim.$id.tsx', "content: 'Origin, original scope, lineage, mutation, suppo", "content: 'Where it started, what was tested, how it spread, how the wording changed, suppo")

// ---------- routes: compound ----------
rep('src/routes/compound.$slug.tsx', "content: `${name}: research footprint, human signal, translation state and claim lineage. Evidence classes kept separate.`", "content: `${name}: what it is, what has been studied, what people say, and how far testing has gone. Studies and stories kept separate.`")
rep('src/routes/compound.$slug.tsx', '<a href="#genome">Research</a><a href="#signal">What people report</a><a href="#translation">How far research has gone</a>', '<a href="#genome">Research</a><a href="#signal">Why people look it up</a><a href="#translation">How far it has been tested</a>')
rep('src/routes/compound.$slug.tsx', '<Section id="snapshot" k="B" title="Snapshot">', '<Section id="snapshot" k="B" title="The quick read">')
rep('src/routes/compound.$slug.tsx', '<Snap title="Regulatory snapshot" onOpen={() => setDrawer(\'regulatory\')}>No regulatory record indexed · <Link to="/status/$compound" params={{ compound: slug }} className="underline">jurisdiction view</Link></Snap>', '<Snap title="Legal status" onOpen={() => setDrawer(\'regulatory\')}>No regulator decisions listed yet · <Link to="/status/$compound" params={{ compound: slug }} className="underline">check by country</Link></Snap>')
rep('src/routes/compound.$slug.tsx', 'detail="The genome renders hollow until a verified record is indexed for this compound."', 'detail="This picture fills in as we add checked studies for this product."')
rep('src/routes/compound.$slug.tsx', 'title="No themes indexed" detail="Research themes appear only after verified records are indexed and classified for this compound."', 'title="No topics yet" detail="Topics show up here once we have checked studies for this product and sorted them."')
rep('src/routes/compound.$slug.tsx', ">{t.pmids.length} verified<", ">{t.pmids.length} checked<")
rep('src/routes/compound.$slug.tsx', '<Section id="claims" k="G" title="Claim lineage" lede="Top associated claims. Each opens the full lineage graph.">', '<Section id="claims" k="G" title="Claims people make" lede="The big claims tied to this product. Open one to see where it came from and how it spread.">')
rep('src/routes/compound.$slug.tsx', 'title="No claim record indexed for this compound" detail="Claims are created only with an origin record or an explicit unresolved-origin state."', 'title="No claims tracked for this product yet" detail="We only add a claim once we can point to where it started, or say clearly that we could not find out."')
rep('src/routes/compound.$slug.tsx', '<Section id="translation" k="H" title="Translation gap" lede="Cell → Mouse → Rat → Larger animal → Human → Controlled human → Approved use — per outcome. Stages light only where a verified record supports them.">', '<Section id="translation" k="H" title="How far it has been tested" lede="From cells in a dish, to mice, rats, bigger animals, people, proper trials, and finally regulator approval. The light stops where the checked studies stop.">')
rep('src/routes/compound.$slug.tsx', '<Section id="independence" k="I" title="Research independence" lede="Ten papers from one laboratory are not ten independent replications.">', '<Section id="independence" k="I" title="How many separate teams" lede="Ten papers from one lab are not ten separate confirmations.">')
rep('src/routes/compound.$slug.tsx', '<p className="label">Distinct last-author groups (proxy)</p>', '<p className="label">Separate senior authors (a rough count of teams)</p>')
rep('src/routes/compound.$slug.tsx', "Institutions, funding and citation links: Not assessed — esummary does not carry affiliations; a Crossref/efetch connector is required.", "Universities, funding and who cites whom: not checked yet. PubMed’s summary does not include that, so it needs another data source.")
rep('src/routes/compound.$slug.tsx', 'title="Not assessed" detail="Independence is estimated only from verified records."', 'title="Not checked yet" detail="We only count teams from studies we have confirmed."')
rep('src/routes/compound.$slug.tsx', '<Section id="contradictions" k="J" title="What doesn\'t fit?" lede="Disagreement is surfaced, not hidden.">', '<Section id="contradictions" k="J" title="What doesn’t fit?" lede="If a study disagrees, it goes here. We do not hide it.">')
rep('src/routes/compound.$slug.tsx', 'title="No contradictory study currently indexed" detail="Null findings, conflicting research and methodological criticism appear here when indexed. A partial relationship above is not a contradiction."', 'title="No study we have checked pushes back yet" detail="Studies that found nothing, disagree, or criticize the method will show up here once we add them. A study that only partly agrees is not the same as one that disagrees."')
rep('src/routes/compound.$slug.tsx', '<Section id="timeline" k="K" title="Timeline" lede="Research and public-signal history, in separate lanes.">', '<Section id="timeline" k="K" title="Timeline" lede="What happened and when. Studies in one lane, real-world reports in another.">')
rep('src/routes/compound.$slug.tsx', '<Section id="sources" k="L" title="Sources" lede="Fully traceable bibliography. Only build-time-verified PMIDs are rendered as citations.">', '<Section id="sources" k="L" title="Sources" lede="Every study we used. Only studies we confirmed on PubMed are shown as sources.">')
rep('src/routes/compound.$slug.tsx', '<p className="label mb-3">Residue table (SSR equivalent of the structure)</p>', '<p className="label mb-3">The building blocks, one by one</p>')
rep('src/routes/compound.$slug.tsx', ">expand provenance →<", ">see where this comes from →<")
rep('src/routes/compound.$slug.tsx', "aria-label={`Research independence map: ${n} distinct last-author groups`}", "aria-label={`Map of separate research teams: ${n} senior authors`}")
rep('src/routes/compound.$slug.tsx', ">node size = records per last-author group · edges to cross-citations: not assessed<", ">bigger circle = more studies from that senior author · who cites whom: not checked yet<")
rep('src/routes/compound.$slug.tsx', "regulatory: 'Legal and approval status'", "regulatory: 'Legal status'")
rep('src/routes/compound.$slug.tsx', "case 'research': return <><p>{n} PMIDs listed in studies.ts for {displayName(c)} resolved against NCBI eutils at build time. Study type and species come from the record title / publication type; tags from the abstract.</p><p>{groups} distinct last-author surname(s) — a proxy, not an institution map.</p></>", "case 'research': return <><p>We list {n} PubMed ID{n === 1 ? '' : 's'} for {displayName(c)} and confirm each one against PubMed before the site is built. The kind of study and what it was tested on come from the study’s title; the topics come from its summary.</p><p>{groups} different senior author{groups === 1 ? '' : 's'} — a rough count of separate teams, not a full map of universities.</p></>")
rep('src/routes/compound.$slug.tsx', "case 'translation': return <p>Stages are lit from claims.ts → translation, which is populated only when a verified record with the matching species / model exists. Nothing is inferred from reviews.</p>", "case 'translation': return <p>A stage lights up only when a confirmed study tested it on that kind of subject. We never guess from review papers.</p>")
rep('src/routes/compound.$slug.tsx', "case 'change': return <p>Derived from claims.ts change history. The only event so far is claim creation, dated 2026-09-20. Nothing has been rewritten.</p>", "case 'change': return <p>This comes from our change log. So far the only event is the day we added the claim, 2026-09-20. Nothing has been rewritten.</p>")
rep('src/routes/compound.$slug.tsx', "case 'regulatory': return <p>No regulatory connector is enabled. The status page shows jurisdiction and date fields with an explicit empty state. An advisory vote is never shown as an approval.</p>", "case 'regulatory': return <p>We have not connected regulator records yet. The legal status page shows each country with an honest “nothing listed yet”. A committee vote is never shown as an approval.</p>")
rep('src/routes/compound.$slug.tsx', "<p>Share cards and research-packet export are in production; they will carry no treatment recommendation.</p>", "<p>Share cards and a printable research packet are coming. Neither will ever include dosing or treatment advice.</p>")

// ---------- routes: others ----------
rep('src/routes/claims.tsx', ">Every claim has a canonical ID.<", ">Every claim, traced back to where it started.<")
rep('src/routes/claims.tsx', ">Each record traces: earliest indexed source, exact experimental result, species, original wording, mutations, contradictions, current evidence state.<", ">For each one you can see the first study it came from, what that study actually tested, how the wording changed as it spread, which studies push back, and our short plain-English reading.<")
rep('src/routes/claims.tsx', "{CLAIMS.length} tracked claims · Claim Inspector (free-text) is in production; results will be constructed from graph entities, never free-form.", "{CLAIMS.length} claims tracked · Soon: paste any claim you saw online and we will check it against the studies we have.")
rep('src/routes/compare.tsx', ">Descriptive, side by side.<", ">Side by side. No hype.<")
rep('src/routes/compare.tsx', ">Up to four compounds. No winner is declared and nothing is &ldquo;best for&rdquo; anything.<", ">Compare up to four. We never pick a winner or say one is &ldquo;best for&rdquo; anything.<")
rep('src/routes/compare.tsx', "{ k: 'Mechanism tags'", "{ k: 'Tags'")
rep('src/routes/compare.tsx', "{ k: 'Research domain'", "{ k: 'Topic'")
rep('src/routes/compare.tsx', "{ k: 'Evidence genome'", "{ k: 'Kinds of studies checked'")
rep('src/routes/compare.tsx', "{ k: 'Translation'", "{ k: 'How far it has been tested'")
rep('src/routes/compare.tsx', ": 'no stage'", ": 'not tested yet'")
rep('src/routes/compare.tsx', "{ k: 'Human research', v: cs.map((c) => (distributionFor(c.slug).human ? `${distributionFor(c.slug).human} verified record(s)` : 'No human study indexed')) }", "{ k: 'Studies in people', v: cs.map((c) => (distributionFor(c.slug).human ? `${distributionFor(c.slug).human} checked stud${distributionFor(c.slug).human === 1 ? 'y' : 'ies'}` : 'None checked yet')) }")
rep('src/routes/compare.tsx', "{ k: 'Human signal', v: cs.map(() => CORPUS.header) }", "{ k: 'Real-world reports', v: cs.map(() => CORPUS.header) }")
rep('src/routes/compare.tsx', "{ k: 'Signal integrity', v: cs.map(() => 'Not assessed — no corpus') }", "{ k: 'How trustworthy is the chatter', v: cs.map(() => 'Not measured yet — no reports collected') }")
rep('src/routes/compare.tsx', "{ k: 'Research independence', v: cs.map((c) => { const s = studiesForCompound(c.slug); return s.length ? `${distinctGroups(s).length} last-author group(s) across ${s.length} record(s)` : 'Not assessed' }) }", "{ k: 'Separate research teams', v: cs.map((c) => { const s = studiesForCompound(c.slug); return s.length ? `${distinctGroups(s).length} senior author(s) across ${s.length} stud${s.length === 1 ? 'y' : 'ies'}` : 'Not checked yet' }) }")
rep('src/routes/compare.tsx', "{ k: 'Research themes', v: cs.map((c) => themesFor(c.slug).filter((t) => t.kind === 'research').map((t) => t.label).join(' · ') || 'No themes indexed') }", "{ k: 'What the studies looked at', v: cs.map((c) => themesFor(c.slug).filter((t) => t.kind === 'research').map((t) => t.label).join(' · ') || 'No topics yet') }")
rep('src/routes/compare.tsx', "{ k: 'Regulatory state', v: cs.map(() => 'No regulatory record indexed (jurisdiction / date required)') }", "{ k: 'Legal status', v: cs.map(() => 'No regulator decisions listed yet (needs country and date)') }")
rep('src/routes/compare.tsx', "{ k: 'Structure provenance'", "{ k: 'Where the 3D shape comes from'")
rep('src/routes/compare.tsx', "{ k: 'Latest evidence change'", "{ k: 'Last update'")
rep('src/routes/coverage.tsx', ">What {BRAND} can and cannot see.<", ">What we can see. What we can’t.<")
rep('src/routes/coverage.tsx', ">{BRAND} never implies &ldquo;the internet says&rdquo;. This page is the denominator for every statement on the site.<", ">We never say &ldquo;the internet says&rdquo;. This page shows exactly which sources are connected, so you know what every number on this site is based on.<")
rep('src/routes/coverage.tsx', ">Public platforms<", ">Social and public sites<")
rep('src/routes/coverage.tsx', "<th>Platform</th><th>Adapter</th><th>State</th>", "<th>Site</th><th>How it would connect</th><th>Status</th>")
rep('src/routes/coverage.tsx', ">Scientific &amp; regulatory sources<", ">Science and regulator sources<")
rep('src/routes/coverage.tsx', "<th>Source</th><th>State</th>", "<th>Source</th><th>Status</th>")
rep('src/routes/corrections.tsx', ">Public correction ledger.<", ">When we get something wrong, it goes here.<")
rep('src/routes/corrections.tsx', ">Every material correction records date, affected record, before, after, reason and source. Old interpretations are never deleted silently.<", ">Every fix is logged with the date, what changed, the old version, the new version, why, and the source. We never quietly delete the old version.<")
rep('src/routes/corrections.tsx', "<th>Date</th><th>Affected record</th><th>Before</th><th>After</th><th>Reason</th><th>Source</th>", "<th>Date</th><th>What changed</th><th>Before</th><th>After</th><th>Why</th><th>Source</th>")
rep('src/routes/corrections.tsx', 'title="No corrections have been issued."', 'title="Nothing to correct yet."')
rep('src/routes/status.$compound.tsx', ">← {displayName(c)} dossier<", ">← Back to {displayName(c)}<")
rep('src/routes/status.$compound.tsx', ">Regulatory status<", ">Where it stands with the law.<")
rep('src/routes/status.$compound.tsx', ">Jurisdiction-specific and date-specific. An advisory vote is never an approval; &ldquo;not prohibited&rdquo; is never &ldquo;approved&rdquo;.<", ">Rules differ by country and change over time. A committee vote is not an approval, and &ldquo;not banned&rdquo; is not the same as &ldquo;approved&rdquo;.<")
rep('src/routes/status.$compound.tsx', "const CATEGORIES = ['Approved use', 'Investigational status', 'Compounding actions', 'Sports restrictions', 'Regulatory warnings', 'Advisory proceedings']", "const CATEGORIES = ['Approved uses', 'Still being studied', 'Pharmacy compounding rules', 'Banned in sports?', 'Official warnings', 'Committee reviews']")
rep('src/routes/status.$compound.tsx', '<span className="label">Jurisdiction</span>', '<span className="label">Country or body</span>')
rep('src/routes/status.$compound.tsx', '<span className="label">As of date</span>', '<span className="label">As of</span>')
rep('src/routes/status.$compound.tsx', ">— no record<", ">— nothing listed yet<")
rep('src/routes/status.$compound.tsx', 'title="No regulatory record indexed" detail="Regulatory connectors (FDA, EMA, WADA…) are not enabled. Nothing is inferred from secondary sources."', 'title="Nothing listed yet" detail="We have not connected regulator records (FDA, EMA, WADA and others). We never guess from second-hand sources."')
rep('src/routes/timeline.tsx', ">Every event carries date, source, what changed, previous state, new state. History is never rewritten silently.<", ">Every entry has a date, a source, what changed, the old version and the new version. We never quietly rewrite history.<")
rep('src/routes/timeline.tsx', ">Research nodes appear and disappear, claim interpretations update and regulatory state changes as you move — but only from ledger entries. Before {dates[0]}, no record existed.<", ">Studies, claim updates and legal changes appear as you move through time. Only real logged entries show up. Before {dates[0]}, there was nothing to log.<")
rep('src/routes/timeline.tsx', ">Ledger: {all.length} event(s) total · What we could responsibly say before {dates[0]}: no record existed.<", ">{all.length} entr{all.length === 1 ? 'y' : 'ies'} in the log · Before {dates[0]}: nothing to show.<")
rep('src/routes/timeline.tsx', "{l === 'signal' ? 'Public signal' : l}", "{l === 'signal' ? 'Real-world reports' : l}")
rep('src/routes/timeline.tsx', ">Timeline · change ledger<", ">Timeline · change log<")
rep('src/routes/timeline.tsx', ">Only show changes that altered a claim interpretation<", ">Only show changes that changed our reading of a claim<")
rep('src/routes/timeline.tsx', ">Now: <span className=\"text-bone\">{now}</span> · {events.length} event{events.length === 1 ? '' : 's'} visible · ledger floor {dates[0]}<", ">Now: <span className=\"text-bone\">{now}</span> · {events.length} entr{events.length === 1 ? 'y' : 'ies'} showing · log starts {dates[0]}<")
rep('src/routes/timeline.tsx', "title: `Timeline / change ledger — ${BRAND}`", "title: `Timeline — ${BRAND}`")
rep('src/routes/learn.tsx', ">The learning current<", ">Start here<")
rep('src/routes/learn.tsx', ">Ideas change as they travel. Enter a lesson, follow the current back to its source, and learn where evidence ends and interpretation begins.<", ">Ideas change as they travel. Pick a lesson, follow it back to the source, and learn where the evidence ends and the opinion begins.<")
rep('src/routes/learn.tsx', ">10 passages · 1 interactive now<br/>new lessons surface as they are verified<", ">10 lessons · 1 ready to try now<br/>more open as we finish checking them<")
rep('src/routes/learn.tsx', ">Choose a passage<", ">Pick a lesson<")
rep('src/routes/learn.tsx', ">Learn to read the waterline.<", ">Learn to spot the real thing.<")
rep('src/routes/learn.tsx', ">Each lesson separates the original record from the versions that formed downstream.<", ">Each lesson shows the original study next to the versions that grew out of it.<")
rep('src/routes/learn.tsx', "content: 'Interactive lessons for navigating molecular research, claims, and evidence.'", "content: 'Short lessons that teach you how to tell a real study from a good story.'")
rep('src/routes/learn.$slug.tsx', ">Drag the slider. The source finding is copied verbatim from a verified abstract. Every later step is illustrative wording — labelled as such.<", ">Drag the slider. Step one is copied word for word from a confirmed study. Every later step is example wording, and it is labelled that way.<")
rep('src/routes/learn.$slug.tsx', ">Struck words are dropped from the previous step. Species, model and uncertainty tend to go first.<", ">Crossed-out words got dropped. What it was tested on, how, and the careful “maybe” words usually go first.<")
rep('src/routes/learn.$slug.tsx', ">Violet words were added. Outcomes, speed and scope tend to arrive last — and were never measured.<", ">Purple words got added. Big results, speed and “works for everything” usually arrive last — and were never measured.<")
rep('src/routes/learn.$slug.tsx', ">This is called claim mutation, not misinformation. Some steps are faithful paraphrases. The point is to see which transformation happened, and to link each one to its source text.<", ">This is not always lying. Some steps are fair summaries. The point is to see exactly which change happened at each step, and to tie every step back to the real study.<")
rep('src/routes/index.tsx', ">Enter the molecular<br/>laboratory.<", ">See it up close.<br/>Then decide.<")
rep('src/routes/saved.tsx', ">Saved<", ">Your shortlist.<")

// ---------- footer ----------
rep('src/components/Footer.tsx', '<b className="text-bone/80">Research and educational information. Final product pricing, payment, fulfillment, and regulatory requirements remain under review.</b>', '<b className="text-bone/80">You must be 21 or older to use this site.</b> Everything here is for research and education. It is not medical advice, and we never tell you how much of anything to take. Talk to a doctor before you change anything about your health. Prices, checkout, shipping and product eligibility are still being finalized.')

// ---------- run ----------
let missing = 0
const touched = new Set()
for (const { file, from, to, all } of R) {
  const path = file
  let src = readFileSync(path, 'utf8')
  if (!src.includes(from)) { console.error(`MISSING in ${file}:\n  ${from.slice(0, 120)}`); missing++; continue }
  src = all ? src.split(from).join(to) : src.replace(from, to)
  writeFileSync(path, src)
  touched.add(file)
}
console.log(`replacements: ${R.length - missing}/${R.length} · files: ${touched.size}`)
if (missing) process.exit(1)
