/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BondTheoryRouteImport } from './routes/bond-theory'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as CoaRouteImport } from './routes/coa'
import { Route as CombinationsRouteImport } from './routes/combinations'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ClaimIdRouteImport } from './routes/claim.$id'
import { Route as CompoundSlugRouteImport } from './routes/compound.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as PulseReviewRouteImport } from './routes/pulse_.review'
import { Route as ResearchToolsIndexRouteImport } from './routes/research-tools.index'
import { Route as ResearchToolsPreclinicalCalculatorRouteImport } from './routes/research-tools.preclinical-calculator'
import { Route as StatusCompoundRouteImport } from './routes/status.$compound'
import { Route as StudyPmidRouteImport } from './routes/study.$pmid'
import { Route as WatchlistSlugRouteImport } from './routes/watchlist.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BondTheoryRoute = BondTheoryRouteImport.update({
  id: '/bond-theory',
  path: '/bond-theory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const CoaRoute = CoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinationsRoute = CombinationsRouteImport.update({
  id: '/combinations',
  path: '/combinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIdRoute = ClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompoundSlugRoute = CompoundSlugRouteImport.update({
  id: '/compound/$slug',
  path: '/compound/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const PulseReviewRoute = PulseReviewRouteImport.update({
  id: '/pulse_/review',
  path: '/pulse/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchToolsIndexRoute = ResearchToolsIndexRouteImport.update({
  id: '/research-tools/',
  path: '/research-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchToolsPreclinicalCalculatorRoute =
  ResearchToolsPreclinicalCalculatorRouteImport.update({
    id: '/research-tools/preclinical-calculator',
    path: '/research-tools/preclinical-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const StatusCompoundRoute = StatusCompoundRouteImport.update({
  id: '/status/$compound',
  path: '/status/$compound',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPmidRoute = StudyPmidRouteImport.update({
  id: '/study/$pmid',
  path: '/study/$pmid',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistSlugRoute = WatchlistSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WatchlistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bond-theory': typeof BondTheoryRoute
  '/claims': typeof ClaimsRoute
  '/coa': typeof CoaRoute
  '/combinations': typeof CombinationsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/coverage': typeof CoverageRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/saved': typeof SavedRoute
  '/shop': typeof ShopRoute
  '/signal': typeof SignalRoute
  '/targets': typeof TargetsRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/waitlist': typeof WaitlistRoute
  '/watchlist': typeof WatchlistRouteWithChildren
  '/claim/$id': typeof ClaimIdRoute
  '/compound/$slug': typeof CompoundSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/pulse/review': typeof PulseReviewRoute
  '/research-tools/preclinical-calculator': typeof ResearchToolsPreclinicalCalculatorRoute
  '/status/$compound': typeof StatusCompoundRoute
  '/study/$pmid': typeof StudyPmidRoute
  '/watchlist/$slug': typeof WatchlistSlugRoute
  '/research-tools/': typeof ResearchToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bond-theory': typeof BondTheoryRoute
  '/claims': typeof ClaimsRoute
  '/coa': typeof CoaRoute
  '/combinations': typeof CombinationsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/coverage': typeof CoverageRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/saved': typeof SavedRoute
  '/shop': typeof ShopRoute
  '/signal': typeof SignalRoute
  '/targets': typeof TargetsRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/waitlist': typeof WaitlistRoute
  '/watchlist': typeof WatchlistRouteWithChildren
  '/claim/$id': typeof ClaimIdRoute
  '/compound/$slug': typeof CompoundSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/pulse/review': typeof PulseReviewRoute
  '/research-tools/preclinical-calculator': typeof ResearchToolsPreclinicalCalculatorRoute
  '/status/$compound': typeof StatusCompoundRoute
  '/study/$pmid': typeof StudyPmidRoute
  '/watchlist/$slug': typeof WatchlistSlugRoute
  '/research-tools': typeof ResearchToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bond-theory': typeof BondTheoryRoute
  '/claims': typeof ClaimsRoute
  '/coa': typeof CoaRoute
  '/combinations': typeof CombinationsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/coverage': typeof CoverageRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/saved': typeof SavedRoute
  '/shop': typeof ShopRoute
  '/signal': typeof SignalRoute
  '/targets': typeof TargetsRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/waitlist': typeof WaitlistRoute
  '/watchlist': typeof WatchlistRouteWithChildren
  '/claim/$id': typeof ClaimIdRoute
  '/compound/$slug': typeof CompoundSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/pulse_/review': typeof PulseReviewRoute
  '/research-tools/preclinical-calculator': typeof ResearchToolsPreclinicalCalculatorRoute
  '/status/$compound': typeof StatusCompoundRoute
  '/study/$pmid': typeof StudyPmidRoute
  '/watchlist/$slug': typeof WatchlistSlugRoute
  '/research-tools/': typeof ResearchToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bond-theory'
    | '/claims'
    | '/coa'
    | '/combinations'
    | '/compare'
    | '/contact'
    | '/corrections'
    | '/coverage'
    | '/explore'
    | '/learn'
    | '/methodology'
    | '/privacy'
    | '/pulse'
    | '/saved'
    | '/shop'
    | '/signal'
    | '/targets'
    | '/terms'
    | '/timeline'
    | '/waitlist'
    | '/watchlist'
    | '/claim/$id'
    | '/compound/$slug'
    | '/learn/$slug'
    | '/pulse/review'
    | '/research-tools/preclinical-calculator'
    | '/status/$compound'
    | '/study/$pmid'
    | '/watchlist/$slug'
    | '/research-tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bond-theory'
    | '/claims'
    | '/coa'
    | '/combinations'
    | '/compare'
    | '/contact'
    | '/corrections'
    | '/coverage'
    | '/explore'
    | '/learn'
    | '/methodology'
    | '/privacy'
    | '/pulse'
    | '/saved'
    | '/shop'
    | '/signal'
    | '/targets'
    | '/terms'
    | '/timeline'
    | '/waitlist'
    | '/watchlist'
    | '/claim/$id'
    | '/compound/$slug'
    | '/learn/$slug'
    | '/pulse/review'
    | '/research-tools/preclinical-calculator'
    | '/status/$compound'
    | '/study/$pmid'
    | '/watchlist/$slug'
    | '/research-tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bond-theory'
    | '/claims'
    | '/coa'
    | '/combinations'
    | '/compare'
    | '/contact'
    | '/corrections'
    | '/coverage'
    | '/explore'
    | '/learn'
    | '/methodology'
    | '/privacy'
    | '/pulse'
    | '/saved'
    | '/shop'
    | '/signal'
    | '/targets'
    | '/terms'
    | '/timeline'
    | '/waitlist'
    | '/watchlist'
    | '/claim/$id'
    | '/compound/$slug'
    | '/learn/$slug'
    | '/pulse_/review'
    | '/research-tools/preclinical-calculator'
    | '/status/$compound'
    | '/study/$pmid'
    | '/watchlist/$slug'
    | '/research-tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BondTheoryRoute: typeof BondTheoryRoute
  ClaimsRoute: typeof ClaimsRoute
  CoaRoute: typeof CoaRoute
  CombinationsRoute: typeof CombinationsRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CorrectionsRoute: typeof CorrectionsRoute
  CoverageRoute: typeof CoverageRoute
  ExploreRoute: typeof ExploreRoute
  LearnRoute: typeof LearnRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  PulseRoute: typeof PulseRoute
  SavedRoute: typeof SavedRoute
  ShopRoute: typeof ShopRoute
  SignalRoute: typeof SignalRoute
  TargetsRoute: typeof TargetsRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  WaitlistRoute: typeof WaitlistRoute
  WatchlistRoute: typeof WatchlistRouteWithChildren
  ClaimIdRoute: typeof ClaimIdRoute
  CompoundSlugRoute: typeof CompoundSlugRoute
  PulseReviewRoute: typeof PulseReviewRoute
  ResearchToolsPreclinicalCalculatorRoute: typeof ResearchToolsPreclinicalCalculatorRoute
  StatusCompoundRoute: typeof StatusCompoundRoute
  StudyPmidRoute: typeof StudyPmidRoute
  ResearchToolsIndexRoute: typeof ResearchToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bond-theory': {
      id: '/bond-theory'
      path: '/bond-theory'
      fullPath: '/bond-theory'
      preLoaderRoute: typeof BondTheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coa': {
      id: '/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof CoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combinations': {
      id: '/combinations'
      path: '/combinations'
      fullPath: '/combinations'
      preLoaderRoute: typeof CombinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$id': {
      id: '/claim/$id'
      path: '/claim/$id'
      fullPath: '/claim/$id'
      preLoaderRoute: typeof ClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compound/$slug': {
      id: '/compound/$slug'
      path: '/compound/$slug'
      fullPath: '/compound/$slug'
      preLoaderRoute: typeof CompoundSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/pulse_/review': {
      id: '/pulse_/review'
      path: '/pulse/review'
      fullPath: '/pulse/review'
      preLoaderRoute: typeof PulseReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-tools/': {
      id: '/research-tools/'
      path: '/research-tools'
      fullPath: '/research-tools/'
      preLoaderRoute: typeof ResearchToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-tools/preclinical-calculator': {
      id: '/research-tools/preclinical-calculator'
      path: '/research-tools/preclinical-calculator'
      fullPath: '/research-tools/preclinical-calculator'
      preLoaderRoute: typeof ResearchToolsPreclinicalCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$compound': {
      id: '/status/$compound'
      path: '/status/$compound'
      fullPath: '/status/$compound'
      preLoaderRoute: typeof StatusCompoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$pmid': {
      id: '/study/$pmid'
      path: '/study/$pmid'
      fullPath: '/study/$pmid'
      preLoaderRoute: typeof StudyPmidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/$slug': {
      id: '/watchlist/$slug'
      path: '/$slug'
      fullPath: '/watchlist/$slug'
      preLoaderRoute: typeof WatchlistSlugRouteImport
      parentRoute: typeof WatchlistRoute
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface WatchlistRouteChildren {
  WatchlistSlugRoute: typeof WatchlistSlugRoute
}

const WatchlistRouteChildren: WatchlistRouteChildren = {
  WatchlistSlugRoute: WatchlistSlugRoute,
}

const WatchlistRouteWithChildren = WatchlistRoute._addFileChildren(
  WatchlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BondTheoryRoute: BondTheoryRoute,
  ClaimsRoute: ClaimsRoute,
  CoaRoute: CoaRoute,
  CombinationsRoute: CombinationsRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CorrectionsRoute: CorrectionsRoute,
  CoverageRoute: CoverageRoute,
  ExploreRoute: ExploreRoute,
  LearnRoute: LearnRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  PulseRoute: PulseRoute,
  SavedRoute: SavedRoute,
  ShopRoute: ShopRoute,
  SignalRoute: SignalRoute,
  TargetsRoute: TargetsRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  WaitlistRoute: WaitlistRoute,
  WatchlistRoute: WatchlistRouteWithChildren,
  ClaimIdRoute: ClaimIdRoute,
  CompoundSlugRoute: CompoundSlugRoute,
  PulseReviewRoute: PulseReviewRoute,
  ResearchToolsPreclinicalCalculatorRoute:
    ResearchToolsPreclinicalCalculatorRoute,
  StatusCompoundRoute: StatusCompoundRoute,
  StudyPmidRoute: StudyPmidRoute,
  ResearchToolsIndexRoute: ResearchToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
