/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BondTheoryRouteImport } from './routes/bond-theory'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ClaimIdRouteImport } from './routes/claim.$id'
import { Route as CompoundSlugRouteImport } from './routes/compound.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as StatusCompoundRouteImport } from './routes/status.$compound'
import { Route as StudyPmidRouteImport } from './routes/study.$pmid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BondTheoryRoute = BondTheoryRouteImport.update({
  id: '/bond-theory',
  path: '/bond-theory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIdRoute = ClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompoundSlugRoute = CompoundSlugRouteImport.update({
  id: '/compound/$slug',
  path: '/compound/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const StatusCompoundRoute = StatusCompoundRouteImport.update({
  id: '/status/$compound',
  path: '/status/$compound',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPmidRoute = StudyPmidRouteImport.update({
  id: '/study/$pmid',
  path: '/study/$pmid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bond-theory': typeof BondTheoryRoute
  '/claims': typeof ClaimsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/coverage': typeof CoverageRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/saved': typeof SavedRoute
  '/signal': typeof SignalRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/claim/$id': typeof ClaimIdRoute
  '/compound/$slug': typeof CompoundSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/status/$compound': typeof StatusCompoundRoute
  '/study/$pmid': typeof StudyPmidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bond-theory': typeof BondTheoryRoute
  '/claims': typeof ClaimsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/coverage': typeof CoverageRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/saved': typeof SavedRoute
  '/signal': typeof SignalRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/claim/$id': typeof ClaimIdRoute
  '/compound/$slug': typeof CompoundSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/status/$compound': typeof StatusCompoundRoute
  '/study/$pmid': typeof StudyPmidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bond-theory': typeof BondTheoryRoute
  '/claims': typeof ClaimsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/coverage': typeof CoverageRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/saved': typeof SavedRoute
  '/signal': typeof SignalRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/claim/$id': typeof ClaimIdRoute
  '/compound/$slug': typeof CompoundSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/status/$compound': typeof StatusCompoundRoute
  '/study/$pmid': typeof StudyPmidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bond-theory'
    | '/claims'
    | '/compare'
    | '/contact'
    | '/corrections'
    | '/coverage'
    | '/explore'
    | '/learn'
    | '/methodology'
    | '/privacy'
    | '/pulse'
    | '/saved'
    | '/signal'
    | '/terms'
    | '/timeline'
    | '/claim/$id'
    | '/compound/$slug'
    | '/learn/$slug'
    | '/status/$compound'
    | '/study/$pmid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bond-theory'
    | '/claims'
    | '/compare'
    | '/contact'
    | '/corrections'
    | '/coverage'
    | '/explore'
    | '/learn'
    | '/methodology'
    | '/privacy'
    | '/pulse'
    | '/saved'
    | '/signal'
    | '/terms'
    | '/timeline'
    | '/claim/$id'
    | '/compound/$slug'
    | '/learn/$slug'
    | '/status/$compound'
    | '/study/$pmid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bond-theory'
    | '/claims'
    | '/compare'
    | '/contact'
    | '/corrections'
    | '/coverage'
    | '/explore'
    | '/learn'
    | '/methodology'
    | '/privacy'
    | '/pulse'
    | '/saved'
    | '/signal'
    | '/terms'
    | '/timeline'
    | '/claim/$id'
    | '/compound/$slug'
    | '/learn/$slug'
    | '/status/$compound'
    | '/study/$pmid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BondTheoryRoute: typeof BondTheoryRoute
  ClaimsRoute: typeof ClaimsRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CorrectionsRoute: typeof CorrectionsRoute
  CoverageRoute: typeof CoverageRoute
  ExploreRoute: typeof ExploreRoute
  LearnRoute: typeof LearnRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  PulseRoute: typeof PulseRoute
  SavedRoute: typeof SavedRoute
  SignalRoute: typeof SignalRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  ClaimIdRoute: typeof ClaimIdRoute
  CompoundSlugRoute: typeof CompoundSlugRoute
  StatusCompoundRoute: typeof StatusCompoundRoute
  StudyPmidRoute: typeof StudyPmidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bond-theory': {
      id: '/bond-theory'
      path: '/bond-theory'
      fullPath: '/bond-theory'
      preLoaderRoute: typeof BondTheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$id': {
      id: '/claim/$id'
      path: '/claim/$id'
      fullPath: '/claim/$id'
      preLoaderRoute: typeof ClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compound/$slug': {
      id: '/compound/$slug'
      path: '/compound/$slug'
      fullPath: '/compound/$slug'
      preLoaderRoute: typeof CompoundSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/status/$compound': {
      id: '/status/$compound'
      path: '/status/$compound'
      fullPath: '/status/$compound'
      preLoaderRoute: typeof StatusCompoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$pmid': {
      id: '/study/$pmid'
      path: '/study/$pmid'
      fullPath: '/study/$pmid'
      preLoaderRoute: typeof StudyPmidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BondTheoryRoute: BondTheoryRoute,
  ClaimsRoute: ClaimsRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CorrectionsRoute: CorrectionsRoute,
  CoverageRoute: CoverageRoute,
  ExploreRoute: ExploreRoute,
  LearnRoute: LearnRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  PulseRoute: PulseRoute,
  SavedRoute: SavedRoute,
  SignalRoute: SignalRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  ClaimIdRoute: ClaimIdRoute,
  CompoundSlugRoute: CompoundSlugRoute,
  StatusCompoundRoute: StatusCompoundRoute,
  StudyPmidRoute: StudyPmidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
